name: FunParticles
author: JusticeMan
version: 1.1
main: Particle.Main
description: A plugin that allows you to use particle effects as a cosmetic!
commands:
  Hearts:
    description: Hearts will pop up around you!
  Flames:
    description: Flames will pop up around you!
  Rainbow:
    description: Two rainbow rings will spiral around you! 
  Halo:
    description: A angelic halo will appear above you!
  SnowFairy:
    description: Fairy wings will pop up behind you!  

    